[package]
name = "tool-derive"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>"]
edition = "2018"

[lib]
name = "tool_derive"
proc-macro = true

[dependencies]
proc-macro2 = "^0.4.6"
quote = "^0.6.3"
syn = "^0.15.1"
